### ISSUE TITLE
This thing needs a name

### ISSUE THREAD

**Issue by paldepind** [paldepind/functional-frontend-architecture#3]
I don't have any good ideas. But it should ideally be something that makes it obvious that the point is to be functional!

**Comment by ericgj** [comment]
Honestly N.F.F.F. is great for what it is right now, in my :book:   It's not a damn framework, it's a demonstration of what's possible pulling together a few key libraries.  :+1:   

For comparison, Mercury in its own way is a collection of libraries, and slapping a name and logo on it always seemed a bit premature to me. Maybe that's just me.

**Comment by raine** [comment]
What is the point where a set of npm modules that complement each other nicely become a framework?

**Comment by dusky3** [comment]
Hi, I think you did an awesome job - I was trying to find frontend framework that would allow me to pactice the real frp in javascript for so long and I thought mithril + kefir is all I can get, but then you released this elm-like beast. It rightly deserves perfect name and I propose FURE or FURE JS, meaning FUnctional-REactive. That's just my 0.02$.
Once again, thank you @paldepind

**Comment by alexeygolev** [comment]
I like it because it isn't really a framework but rather a set of tools and an way to engineer the apps. I think the best name for this "framework" is No Framework:)
There are various ways of approaching the same task even using the same tools. I have (my version)[https://github.com/alexeygolev/elm-architecture-using-ramda-and-flyd] that maybe actually merged into this repository as a different approach if @paldepind likes idea. I think the best thing would be to collect different approaches using different tools here. But that's up to the maintainers.

**Comment by gaearon** [comment]
I also like that it's not explicitly a framework.

**Comment by paldepind** [comment]
I agree with @alexeygolev. These ideas can be understood independent of implementation and they can be implemented in various ways with various libraries. I'd like for this repository to collect all the various ways to put the pieces together.

Actually taking "framework" out of the repository name would probably be a good idea.

**Comment by paldepind** [comment]
I've updated the readme with small descriptions of the different examples and a section on the different libraries that one can use to implement the architecture. I hope that this makes it clearer that the repository wants to host implementations using different techniques and libraries.

I really think this repository needs a new name that does not include the word "framework". Simply "functional-frontend-architecture" is appropriate. But maybe we need something more recognizable.

**Comment by paldepind** [comment]
I've taken out the "noname" and changed "framework" to "architecture". I'm keeping the issue open in case anyone has a better idea.
